### ISSUE TITLE
tagStack.last() fails all over

### ISSUE THREAD

**Issue by tj** [tautologistics/node-htmlparser#14]
for me. however when I change it to `tagStack['-1']()` its fine, haha.. no clue what you are doing here, but yeah here is my trace. Which is used with jsdom for parsing even a simple string like `<html><body><p>foo</p></body></html>`.

```
    register.test.js test GET /signup: TypeError: Property 'last' of object [object Object] is not a function
     at DefaultHandler.DefaultHandler$handleElement [as handleElement] (/Users/tj/Projects/LearnBoost/tests/functional/support/htmlparser/lib/htmlparser.js:694:26)
     at DefaultHandler.DefaultHandler$writeTag [as writeTag] (/Users/tj/Projects/LearnBoost/tests/functional/support/htmlparser/lib/htmlparser.js:612:8)
     at Parser.Parser$writeHandler [as writeHandler] (/Users/tj/Projects/LearnBoost/tests/functional/support/htmlparser/lib/htmlparser.js:443:20)
     at Parser.Parser$parseTags [as parseTags] (/Users/tj/Projects/LearnBoost/tests/functional/support/htmlparser/lib/htmlparser.js:383:8)
     at Parser.Parser$parseChunk [as parseChunk] (/Users/tj/Projects/LearnBoost/tests/functional/support/htmlparser/lib/htmlparser.js:95:8)
     at Parser.Parser$parseComplete [as parseComplete] (/Users/tj/Projects/LearnBoost/tests/functional/support/htmlparser/lib/htmlparser.js:86:8)
     at Object.ParseHtml (/Users/tj/Projects/LearnBoost/tests/functional/support/jsdom/lib/jsdom/browser/htmltodom.js:62:16)
     at HtmlToDom.appendHtmlToElement (/Users/tj/Projects/LearnBoost/tests/functional/support/jsdom/lib/jsdom/browser/htmltodom.js:73:27)
     at Object.innerHTML (/Users/tj/Projects/LearnBoost/tests/functional/support/jsdom/lib/jsdom/browser/index.js:295:27)
     at Object.write (/Users/tj/Projects/LearnBoost/tests/functional/support/jsdom/lib/jsdom/browser/index.js:202:22)
     at Object.jsdom (/Users/tj/Projects/LearnBoost/tests/functional/support/jsdom/lib/jsdom.js:30:9)
     at /Users/tj/Projects/LearnBoost/tests/functional/register.test.js:26:23
     at next (/Users/tj/Projects/LearnBoost/tests/integration/support/expresso/bin/expresso:769:25)
     at runSuite (/Users/tj/Projects/LearnBoost/tests/integration/support/expresso/bin/expresso:787:6)
     at check (/Users/tj/Projects/LearnBoost/tests/integration/support/expresso/bin/expresso:648:16)
     at runFile (/Users/tj/Projects/LearnBoost/tests/integration/support/expresso/bin/expresso:652:10)
     at Array.forEach (native)
     at runFiles (/Users/tj/Projects/LearnBoost/tests/integration/support/expresso/bin/expresso:629:13)
     at run (/Users/tj/Projects/LearnBoost/tests/integration/support/expresso/bin/expresso:598:5)
     at Object.<anonymous> (/Users/tj/Projects/LearnBoost/tests/integration/support/expresso/bin/expresso:851:13)
     at Module._compile (node.js:462:23)
     at Module._loadScriptSync (node.js:469:10)
     at Module.loadSync (node.js:338:12)
     at Object.runMain (node.js:522:24)
     at Array.0 (node.js:756:12)
     at EventEmitter._tickCallback (node.js:55:22)
     at node.js:773:9
```

**Comment by tautologistics** [comment]
Not all browsers support negative array indices so I provide a last() method on the array to easily get at the last element.

I tested your HTML snippet with the my latest version (from both GitHub and NPM) and it works:

```
var sys = require("sys");
var htmlparser = require("htmlparser");

var html = "<html><body><p>foo</p></body></html>";

var handler = new htmlparser.DefaultHandler(function(err, dom) {
    if (err)
        sys.debug("Error: " + err);
    else
        sys.debug(sys.inspect(dom, false, null));
}, { enforceEmptyTags: true });
var parser = new htmlparser.Parser(handler);
parser.parseComplete(html);
```

...produces the output:

```
DEBUG: [ { raw: 'html',
    data: 'html',
    type: 'tag',
    name: 'html',
    children: 
     [ { raw: 'body',
         data: 'body',
         type: 'tag',
         name: 'body',
         children: 
          [ { raw: 'p',
              data: 'p',
              type: 'tag',
              name: 'p',
              children: [ { raw: 'foo', data: 'foo', type: 'text' } ] } ] } ] } ]
```

No errors occur. What version of the parser lib are you working with?

**Comment by tj** [comment]
17b9274

 '-1' is a prop just like anything else. Also function assign names are implied, so you dont need this grossness :p "DefaultHandler$_tagStack$last"

**Comment by tautologistics** [comment]
Sorry, I have been working with perl again lately, which allows a negative array index. Not sure sure why `tagStack.last()` fails but `tagStack['-1']()` does not; what happens for `tagStack['last']()`?

The reason for the "grossness" is to have more useful stack traces when an exception is thrown. Without the explicit naming, the functions names are blank and without the "Class$Method" format, classes that have the same method names will leave ambiguous call stacks.

See this gist for example code:

https://gist.github.com/748644

The output of the example is the following:

No method names
    ()@file:///.../example.html:7
    @file:///.../example.html:31

Short method names:
    ShortName()@file:///.../example.html:10
    @file:///.../example.html:37

Full method names:
    Example$FullName()@file:///.../example.html:13
    @file:///.../example.html:43

Short method names with multiple classes with the same method names (ambiguous):
    ShortName()@file:///.../example.html:10
    ShortName()@file:///.../example.html:21
    @file:///.../example.html:49

Full method names with multiple classes with the same method names (concise):
    Example$FullName()@file:///.../example.html:13
    ExampleDupeMethods$FullName()@file:///.../example.html:24
    @file:///.../example.html:55
