### ISSUE TITLE
maybe you should update your documents~

### ISSUE THREAD

**Issue by dreamflywang** [tautologistics/node-htmlparser#53]
/Users/owen/Documents/workspace/node-htmlparser/snippet.js:8
var handler = new htmlparser.DefaultHandler(function(err, dom) {
              ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/owen/Documents/workspace/node-htmlparser/snippet.js:8:15)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

**Comment by 75lb** [comment]
bump.

**Comment by cistov** [comment]
It's likely related to #57

**Comment by nukulb** [comment]
bump, just ran into this in the latest from bower install.
